export {
  deleteAnnouncement,
  deleteCategory,
  deleteManagedProfile,
  getReportSummary,
  listAdminAnnouncements,
  listAuditLogs,
  listCategories,
  listProfiles,
  listSlaSettings,
  listTechnicians,
  saveAnnouncement,
  saveCategory,
  saveManagedProfile,
  saveSlaSetting,
} from "@/services/api/adminApiService";
