export {
  addComment,
  addTicketAttachments,
  createTicket,
  deleteTicket,
  getDashboardData,
  getTicketDetail,
  listAnnouncements,
  listNotifications,
  listTickets,
  markAllNotificationsRead,
  markNotificationRead,
  NOTIFICATIONS_CHANGED_EVENT,
  subscribeToNotifications,
  updateTicket,
} from "@/services/api/ticketApiService";
